#!/usr/bin/env python3
"""Run Hylianscan release validation checks."""

from __future__ import annotations

import shlex
import shutil
import subprocess
import sys
from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]


def format_command(command: list[str]) -> str:
    """Return a shell-readable command string for logs."""
    return " ".join(shlex.quote(part) for part in command)


def print_step(title: str) -> None:
    """Print a clear validation step header."""
    print(f"\n==> {title}", flush=True)


def run_step(title: str, command: list[str]) -> None:
    """Run one validation command and stop immediately on failure."""
    print_step(title)
    print(f"$ {format_command(command)}", flush=True)

    try:
        subprocess.run(
            command,
            cwd=REPOSITORY_ROOT,
            check=True,
            stderr=subprocess.STDOUT,
        )
    except FileNotFoundError as error:
        print(f"\n[FAIL] Command not found: {command[0]}", file=sys.stderr)
        raise SystemExit(1) from error
    except subprocess.CalledProcessError as error:
        print(f"\n[FAIL] Command failed: {format_command(command)}", file=sys.stderr)
        raise SystemExit(error.returncode) from error


def main() -> int:
    """Execute the release validation workflow."""
    python = sys.executable

    run_step("Version command", [python, "hylianscan.py", "--version"])
    run_step("Help command", [python, "hylianscan.py", "--help"])
    run_step(
        "Compile validation",
        [python, "-m", "compileall", "-q", "hylianscan.py", "core", "modules", "tests"],
    )
    run_step(
        "Unit test validation",
        [python, "-m", "unittest", "discover", "-s", "tests", "-p", "test_*.py", "-v"],
    )
    run_step("Package metadata dry run", [python, "-m", "pip", "install", "--dry-run", "."])
    cleanup_generated_metadata()

    if shutil.which("git"):
        run_step("Git whitespace validation", ["git", "diff", "--check"])
    else:
        print_step("Git whitespace validation")
        print("git was not found on PATH; skipping git diff --check.", flush=True)

    print_step("Release validation completed successfully")
    return 0


def cleanup_generated_metadata() -> None:
    """Remove package metadata generated by pip dry-run."""
    metadata_path = REPOSITORY_ROOT / "hylianscan.egg-info"

    if metadata_path.exists():
        shutil.rmtree(metadata_path)


if __name__ == "__main__":
    raise SystemExit(main())
